@startuml
left to right direction
actor Empregado_Armazém
Empregado_Balcão -- Empregado_Armazém
rectangle Operações {
    Empregado_Armazém -- (Ver Stock Produtos)
    Empregado_Armazém -- (Consultar Pedidos de Restock)
    Empregado_Armazém -- (Adicionar Quantidade Produtos)
}
@enduml
